export const privateTourRequests = [
	{
		user: '612ecb21249dab001fc9d0fc',
		destination: 'Hunza',
		route: ['Islamabad', 'Naran', 'Hunza'],
		durationDays: 5,
		travelers: 2,
		description: 'Looking for a private tour of Hunza Valley with a local guide',
		departureDate: '2023-06-15',
		departureTime: '09:00 AM',
		departureLocation: 'Islamabad Airport',
		budget: 50000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	},
	{
		user: '612ecb21249dab001fc9d0fc',
		destination: 'Swat',
		route: ['Islamabad', 'Mingora', 'Kalam', 'Mahodand Lake', 'Swat'],
		durationDays: 7,
		travelers: 4,
		description: 'Looking for a private tour of Swat Valley with comfortable accommodation',
		departureDate: '2023-07-10',
		departureTime: '08:00 AM',
		departureLocation: 'Islamabad',
		budget: 80000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	},
	{
		user: '612ecb21249dab001fc9d0fc',
		destination: 'Naran Kaghan',
		route: ['Islamabad', 'Naran', 'Jalkhad', 'Lake Saif ul Malook'],
		durationDays: 3,
		travelers: 3,
		description: 'Looking for a private tour of Naran Kaghan Valley with a reliable transport',
		departureDate: '2023-06-20',
		departureTime: '10:00 AM',
		departureLocation: 'Islamabad',
		budget: 40000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	},
	{
		user: '612ecb21249dab001fc9d0fc',
		destination: 'Gilgit Baltistan',
		route: ['Islamabad', 'Gilgit', 'Hunza', 'Khunjerab Pass'],
		durationDays: 10,
		travelers: 6,
		description: 'Looking for a private tour of Gilgit Baltistan region with camping experience',
		departureDate: '2023-08-05',
		departureTime: '07:00 AM',
		departureLocation: 'Islamabad',
		budget: 120000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	},
	{
		user: '612ecb21249dab001fc9d0fc',
		destination: 'Kashmir',
		route: ['Lahore', 'Muzaffarabad', 'Keran', 'Neelum Valley', 'Kundal Shahi'],
		durationDays: 6,
		travelers: 4,
		description: 'Looking for a private tour of Neelum Valley in Azad Kashmir',
		departureDate: '2023-07-25',
		departureTime: '06:00 AM',
		departureLocation: 'Lahore',
		budget: 90000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	},
	{
		user: '615z8f331056b4042d0f674c',
		destination: 'Naran',
		route: ['Islamabad', 'Balakot', 'Naran'],
		durationDays: 5,
		travelers: 4,
		description: 'We are a family of 4 and want to explore Naran and nearby areas.',
		departureDate: '2022-07-01',
		departureTime: '08:00 AM',
		departureLocation: 'Islamabad',
		budget: 100000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	},
	{
		user: '615z8f331056b4042d0f674c',
		destination: 'Skardu',
		route: ['Islamabad', 'Chilas', 'Skardu'],
		durationDays: 7,
		travelers: 2,
		description: 'We are a couple looking to explore Skardu and surrounding areas.',
		departureDate: '2022-08-15',
		departureTime: '06:00 AM',
		departureLocation: 'Islamabad',
		budget: 150000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	},
	{
		user: '6162f4f97c4cc7947c0f422a',
		destination: 'Swat',
		route: ['Islamabad', 'Mingora', 'Kalam'],
		durationDays: 6,
		travelers: 8,
		description: 'We are a group of friends looking for a fun trip to Swat and nearby areas.',
		departureDate: '2023-06-01',
		departureTime: '09:00 AM',
		departureLocation: 'Islamabad',
		budget: 200000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	},
	{
		user: '612345678901234567890123',
		destination: 'Swat Valley',
		route: ['Islamabad', 'Mingora', 'Kalam', 'Malam Jabba', 'Marghazar'],
		durationDays: 7,
		travelers: 2,
		description: 'Looking for a private tour package for two people to explore the natural beauty of Swat Valley',
		departureDate: new Date('2023-08-15'),
		departureTime: '08:00 AM',
		departureLocation: 'Islamabad',
		budget: 80000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	},
	{
		user: '612345678901234567890123',
		destination: 'Naran & Kaghan Valley',
		route: ['Islamabad', 'Naran', 'Saif-ul-Malook Lake', 'Babusar Top', 'Lulusar Lake'],
		durationDays: 5,
		travelers: 4,
		description: 'Looking for a private tour package for four people to explore the stunning scenery of Naran and Kaghan Valley',
		departureDate: new Date('2023-06-20'),
		departureTime: '09:00 AM',
		departureLocation: 'Islamabad',
		budget: 120000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	},
	{
		user: '612345678901234567890123',
		destination: 'Chitral',
		route: ['Islamabad', 'Dir', 'Lowari Tunnel', 'Chitral'],
		durationDays: 6,
		travelers: 3,
		description: 'Looking for a private tour package for three people to explore the cultural heritage and natural beauty of Chitral',
		departureDate: new Date('2023-09-10'),
		departureTime: '07:00 AM',
		departureLocation: 'Islamabad',
		budget: 90000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	},
	{
		user: '612345678901234567890123',
		destination: 'Hunza Valley',
		route: ['Islamabad', 'Gilgit', 'Hunza', 'Khunjerab Pass'],
		durationDays: 8,
		travelers: 2,
		description: 'Looking for a private tour package for two people to explore the scenic beauty and culture of Hunza Valley',
		departureDate: new Date('2023-07-05'),
		departureTime: '10:00 AM',
		departureLocation: 'Islamabad',
		budget: 100000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	},
	{
		user: '612345678901234567890123',
		destination: 'Kashmir',
		route: ['Islamabad', 'Muzaffarabad', 'Neelum Valley', 'Keran', 'Sharda'],
		durationDays: 6,
		travelers: 4,
		description: 'Looking for a private tour package for four people to explore the breathtaking views of Neelum Valley and Kashmir',
		departureDate: new Date('2023-10-20'),
		departureTime: '06:00 AM',
		departureLocation: 'Islamabad',
		budget: 140000,
		bid: [],
		status: 'pending',
		organizer: null,
		price: 0
	}
];
